apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
---  
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
