apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/tom9eiger/example-application/frontend-demo:latest
        imagePullPolicy: Always
        env:
          - name: BACKEND_URL
            value: "http://flask-api-service.workshop-basic-app.svc.cluster.local"
        ports:
        - containerPort: 80
