apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
---  
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
